#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server with scp:
# +Accepts 4 parameters
# +The path to the file to be transferred
# +The IP of the server we want to transfer the file to
# +The username scp connects with
# +The path to the SSH private key that scp uses
# +Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
