#!/usr/bin/env bash
# Install nginx on your web-01 server
# +Nginx should be listening on port 80
# +When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# +As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# +You can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# printf %s "server {
#    listen	80 default_server;
#    listen	[::]:80 default_server;
#    root	/var/nginx/html;
#    index	index index.html index.htm index.nginx-debian.html;
#    server_name _;
#    location / {
#                try_files $uri $uri/ =404;
#        }
#" > /etc/nginx/sites-available/default
sudo service nginx start
