#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Requirements:
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf %s "server {
    listen	80 default_server;
    listen	[::]:80 default_server;
    root	/var/www/html;
    index	index index.html index.htm index.nginx-debian.html;
    location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
    error_page 404 /404.html;
    location = /404.html {
                root /var/www/html;
                internal;
        }
}
" > /etc/nginx/sites-available/default
sudo service nginx restart
