#!/usr/bin/ev bash
# A MySQL dump that back up all MySQL databases
# Archives the file using tar.gz

mysqldump -u root -p "$1" --all-databases > backup.sql
tar -cvfz "$(date +'%d-%m-%y').tar.gz" backup.sql
