#!/usr/bin/env bash
# creates the file "/var/run/myscript.pid" containing its PID
# Displays "To infinity and beyond" indefinitely
# traps SIGTERM SIGINT and SIGQUIT and quit when SIGQUIT and SIGTERM signals show

clean()
{
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command' && clean" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "clean" SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
