#!/usr/bin/env bash
# indefinite loop that traps SIGTERM  SIGINT SIGQUIT signals
# creates a file containing its PID

echo $$ > /var/run/myscript.pid

i=0
while [ $i -lt 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
done
