#!/usr/bin/env bash
# manages the file manage_my_process with the args of start, stop, restart

start()
{
        ./manage_my_process &
        echo "$$" >> /var/run/my_process.pid
        echo "manage_my_process started"	
}

stop()
{
	pkill -f ./manage_my_process
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
}

restart()
{
        pkill -f ./manage_my_process
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo "$$" >> /var/run/my_process.pid
        echo "manage_my_process restarted"
}

if [ "$1" == "start" ] 
then
	start

elif [ "$1" == "stop" ]
then
	stop

elif [ "$1" == "restart" ]
then
	restart

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
