#!/usr/bin/env bash
# Read file and displays specific fields
# Username, user-id, and home directory path for user of a file

while read -r line
do
	echo "$line" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
