#!/usr/bin/env bash
# read file and displays specific fields
# username, user-id, and home directory path for user of a file

while read line
do
	echo "$line" | cut -d ':' -f1,3,6
done < "/etc/passwd"
