#!/usr/bin/env bash
# Prints numbers and associated superstition

n=1
while [ $n -le 20 ]
do
        echo $n
        case $n in
                "4" )
                        echo "bad luck from Chine" ;;
                "9" )
                        echo "bad luck from Japan" ;;
                "17" )
                        echo "bad luck from Italy" ;;
        esac
        n=$(( n+1 ))
done
