#!/usr/bin/env bash
# script displays time for 12 hrs and 59 min

hour=0
while [ $hour -le 12 ]
do
        echo "Hour: $hour"
        minute=1
        while [ $minute -lt 60 ]
        do
                echo "$minute"
                (( minute++ ))
        done
        (( hour++ ))
done
