#!/usr/bin/env bash
# checks for file present and if it is empty and a regualr file

F="school"
if [[ -e $F ]]
then
	echo "school file exists"
	if [[ -s $F ]]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [[ -f $F ]]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
