#!/usr/bin/env bash
# fix nginx to run as user "nginx" on port 8080
pkill apache2
chmod 700 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
